# Generated by Django 3.1.4 on 2020-12-22 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blogcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
